### ISSUE TITLE
Create an item / product carousel using bootstrap carousel

### ISSUE THREAD

**Issue by buddhikaherath92-dev** [Developers-In/item-carousels#1]
We need a carousel-like following using the built-in bootstrap carousel. 
** Use a new branch for this task
![multiple-item-product-carousel](https://user-images.githubusercontent.com/69967705/93730062-a3f3ca80-fbe4-11ea-970a-f879c555bc4f.png)

This needs to be mobile responsive as following
-> in desktop view it needs to show 4 items
-> in tab view it needs to show 2 items
-> in mobile view it needs to show 1 item

**Comment by LalithK90** [comment]
@thilina19 
after 2.00pm start to this
