### ISSUE TITLE
Create an item / product carousel using slick carousel 

### ISSUE THREAD

**Issue by buddhikaherath92-dev** [Developers-In/item-carousels#2]
We need a carousel-like following using slick carousel
** Use a new branch for this task
![multiple-item-product-carousel](https://user-images.githubusercontent.com/69967705/93730156-077df800-fbe5-11ea-95e2-5bf9ebb0ca62.png)

This needs to be mobile responsive as following
-> in desktop view it needs to show 4 items
-> in tab view it needs to show 2 items

**Comment by thilina19** [comment]
Add a slick carousel update it as a request
![image](https://user-images.githubusercontent.com/8110236/94451619-3d664200-01cc-11eb-964e-44b687156d50.png)
